/**
 * Script to create diverse onboarding profiles for test users
 * Creates profiles that are diverse but groupable by interests, personalities, and food preferences
 */

require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

// Define diverse profile data that creates natural groupings
const profileTemplates = [
  // Group 1: Young Tech Professionals (5 users) - Similar interests, varied food preferences
  {
    education_level: 'bachelor',
    school: 'Stanford University',
    industry: 'Technology',
    job_title: 'Software Engineer',
    company: 'Google',
    ethnicity: 'Asian',
    nationality: 'American',
    religion: 'None',
    relationship_status: 'single',
    height_feet: 5,
    height_inches: 10,
    personality_traits: ['Analytical', 'Curious', 'Ambitious'],
    mbti_type: 'INTJ',
    lead_conversations: 3,
    willing_compromise: 4,
    seek_experiences: 5,
    roles: ['Question-asker', 'Quiet observer'],
    conversation_style: 'Thoughtful',
    early_bird_night_owl: 4,
    active_person: 3,
    punctuality: 5,
    work_life_balance: 3,
    substances: ['Alcohol'],
    dietary_restrictions: 'Vegetarian',
    food_budget: 40,
    spicy_level: 4,
    drinking_level: 3,
    adventurous_level: 4,
    dining_atmospheres: ['casual', 'lively'],
    dinner_duration: '45-90 min',
    zip_code: '94301',
    travel_distance: 5,
    food_craving: 'Thai food',
    cuisines_to_try: ['Thai', 'Korean', 'Japanese'],
    cuisines_to_avoid: ['Fast food'],
    interests: ['Coding', 'AI', 'Gaming', 'Startups'],
    hobbies: ['Programming', 'Video games', 'Reading tech blogs'],
    hoping_to_meet: 'Fellow tech enthusiasts and startup founders',
    interesting_fact: 'Built my first app at age 15'
  },
  {
    education_level: 'master',
    school: 'UC Berkeley',
    industry: 'Technology',
    job_title: 'Product Manager',
    company: 'Meta',
    ethnicity: 'White',
    nationality: 'American',
    religion: 'Agnostic',
    relationship_status: 'dating',
    height_feet: 6,
    height_inches: 1,
    personality_traits: ['Outgoing', 'Strategic', 'Creative'],
    mbti_type: 'ENFP',
    lead_conversations: 5,
    willing_compromise: 4,
    seek_experiences: 5,
    roles: ['Connector', 'Host'],
    conversation_style: 'Energetic',
    early_bird_night_owl: 3,
    active_person: 4,
    punctuality: 4,
    work_life_balance: 4,
    substances: ['Alcohol', 'Weed'],
    dietary_restrictions: '',
    food_budget: 60,
    spicy_level: 3,
    drinking_level: 4,
    adventurous_level: 5,
    dining_atmospheres: ['lively', 'fine_dining'],
    dinner_duration: '90+ min',
    zip_code: '94107',
    travel_distance: 8,
    food_craving: 'Sushi',
    cuisines_to_try: ['Peruvian', 'Ethiopian', 'Lebanese'],
    cuisines_to_avoid: [],
    interests: ['Product design', 'Startups', 'Venture capital', 'Travel'],
    hobbies: ['Networking', 'Wine tasting', 'Hiking'],
    hoping_to_meet: 'Entrepreneurs and creative professionals',
    interesting_fact: 'Traveled to 30 countries before turning 30'
  },
  {
    education_level: 'bachelor',
    school: 'San Jose State',
    industry: 'Technology',
    job_title: 'Data Scientist',
    company: 'Apple',
    ethnicity: 'Hispanic',
    nationality: 'American',
    religion: 'Catholic',
    relationship_status: 'single',
    height_feet: 5,
    height_inches: 7,
    personality_traits: ['Analytical', 'Friendly', 'Methodical'],
    mbti_type: 'ISTJ',
    lead_conversations: 2,
    willing_compromise: 5,
    seek_experiences: 3,
    roles: ['Quiet observer', 'Question-asker'],
    conversation_style: 'Reserved',
    early_bird_night_owl: 2,
    active_person: 3,
    punctuality: 5,
    work_life_balance: 3,
    substances: ['Alcohol'],
    dietary_restrictions: 'Gluten-free',
    food_budget: 35,
    spicy_level: 5,
    drinking_level: 2,
    adventurous_level: 3,
    dining_atmospheres: ['casual', 'quiet'],
    dinner_duration: '30-45 min',
    zip_code: '95014',
    travel_distance: 4,
    food_craving: 'Mexican food',
    cuisines_to_try: ['Spanish', 'Argentinian', 'Brazilian'],
    cuisines_to_avoid: ['Very spicy Asian'],
    interests: ['Data science', 'Machine learning', 'Statistics'],
    hobbies: ['Running', 'Cooking', 'Podcasts'],
    hoping_to_meet: 'People interested in data and analytics',
    interesting_fact: 'Can solve a Rubiks cube in under a minute'
  },
  {
    education_level: 'bachelor',
    school: 'Carnegie Mellon',
    industry: 'Technology',
    job_title: 'UX Designer',
    company: 'Airbnb',
    ethnicity: 'Black',
    nationality: 'American',
    religion: 'Christian',
    relationship_status: 'married',
    height_feet: 5,
    height_inches: 5,
    personality_traits: ['Creative', 'Empathetic', 'Observant'],
    mbti_type: 'INFJ',
    lead_conversations: 3,
    willing_compromise: 4,
    seek_experiences: 4,
    roles: ['Storyteller', 'Connector'],
    conversation_style: 'Warm',
    early_bird_night_owl: 2,
    active_person: 4,
    punctuality: 4,
    work_life_balance: 5,
    substances: ['None'],
    dietary_restrictions: 'Pescatarian',
    food_budget: 45,
    spicy_level: 2,
    drinking_level: 1,
    adventurous_level: 4,
    dining_atmospheres: ['casual', 'artistic'],
    dinner_duration: '45-90 min',
    zip_code: '94103',
    travel_distance: 6,
    food_craving: 'Mediterranean',
    cuisines_to_try: ['Greek', 'Turkish', 'Moroccan'],
    cuisines_to_avoid: ['Heavy meat dishes'],
    interests: ['Design', 'Art', 'Psychology', 'User research'],
    hobbies: ['Sketching', 'Museum visits', 'Photography'],
    hoping_to_meet: 'Creative professionals and artists',
    interesting_fact: 'Designed an app that won a national competition'
  },
  {
    education_level: 'doctorate',
    school: 'MIT',
    industry: 'Technology',
    job_title: 'AI Research Scientist',
    company: 'OpenAI',
    ethnicity: 'Middle Eastern',
    nationality: 'American',
    religion: 'Muslim',
    relationship_status: 'single',
    height_feet: 5,
    height_inches: 11,
    personality_traits: ['Intellectual', 'Passionate', 'Focused'],
    mbti_type: 'INTP',
    lead_conversations: 4,
    willing_compromise: 3,
    seek_experiences: 4,
    roles: ['Question-asker', 'Quiet observer'],
    conversation_style: 'Academic',
    early_bird_night_owl: 5,
    active_person: 2,
    punctuality: 3,
    work_life_balance: 2,
    substances: ['None'],
    dietary_restrictions: 'Halal',
    food_budget: 50,
    spicy_level: 4,
    drinking_level: 1,
    adventurous_level: 3,
    dining_atmospheres: ['quiet', 'casual'],
    dinner_duration: '45-90 min',
    zip_code: '94025',
    travel_distance: 7,
    food_craving: 'Middle Eastern',
    cuisines_to_try: ['Persian', 'Turkish', 'Pakistani'],
    cuisines_to_avoid: ['Pork dishes'],
    interests: ['AI', 'Machine learning', 'Philosophy', 'Science'],
    hobbies: ['Reading research papers', 'Chess', 'Debate'],
    hoping_to_meet: 'Intellectuals and researchers',
    interesting_fact: 'Published 5 papers in top AI conferences'
  },

  // Group 2: Finance Professionals (4 users) - Similar work culture, different personalities
  {
    education_level: 'master',
    school: 'Wharton',
    industry: 'Finance',
    job_title: 'Investment Banker',
    company: 'Goldman Sachs',
    ethnicity: 'White',
    nationality: 'American',
    religion: 'Jewish',
    relationship_status: 'single',
    height_feet: 5,
    height_inches: 9,
    personality_traits: ['Ambitious', 'Competitive', 'Charismatic'],
    mbti_type: 'ENTJ',
    lead_conversations: 5,
    willing_compromise: 2,
    seek_experiences: 4,
    roles: ['Host', 'Connector'],
    conversation_style: 'Assertive',
    early_bird_night_owl: 1,
    active_person: 4,
    punctuality: 5,
    work_life_balance: 2,
    substances: ['Alcohol', 'Tobacco'],
    dietary_restrictions: 'Kosher',
    food_budget: 80,
    spicy_level: 3,
    drinking_level: 5,
    adventurous_level: 4,
    dining_atmospheres: ['fine_dining', 'business'],
    dinner_duration: '90+ min',
    zip_code: '94111',
    travel_distance: 10,
    food_craving: 'Steak',
    cuisines_to_try: ['French', 'Japanese', 'Italian'],
    cuisines_to_avoid: ['Cheap fast food'],
    interests: ['Markets', 'Economics', 'Golf', 'Networking'],
    hobbies: ['Golf', 'Sailing', 'Wine collecting'],
    hoping_to_meet: 'High achievers and business leaders',
    interesting_fact: 'Closed a $100M deal in my first year'
  },
  {
    education_level: 'bachelor',
    school: 'NYU Stern',
    industry: 'Finance',
    job_title: 'Financial Analyst',
    company: 'Morgan Stanley',
    ethnicity: 'Asian',
    nationality: 'Chinese',
    religion: 'Buddhist',
    relationship_status: 'dating',
    height_feet: 5,
    height_inches: 6,
    personality_traits: ['Detail-oriented', 'Calm', 'Reliable'],
    mbti_type: 'ISFJ',
    lead_conversations: 2,
    willing_compromise: 5,
    seek_experiences: 3,
    roles: ['Quiet observer', 'Question-asker'],
    conversation_style: 'Polite',
    early_bird_night_owl: 2,
    active_person: 3,
    punctuality: 5,
    work_life_balance: 3,
    substances: ['Alcohol'],
    dietary_restrictions: '',
    food_budget: 50,
    spicy_level: 3,
    drinking_level: 3,
    adventurous_level: 3,
    dining_atmospheres: ['quiet', 'casual'],
    dinner_duration: '45-90 min',
    zip_code: '94104',
    travel_distance: 5,
    food_craving: 'Chinese hot pot',
    cuisines_to_try: ['Korean', 'Vietnamese', 'Thai'],
    cuisines_to_avoid: ['Very greasy food'],
    interests: ['Finance', 'Real estate', 'Photography'],
    hobbies: ['Photography', 'Hiking', 'Meditation'],
    hoping_to_meet: 'Professionals interested in finance and investing',
    interesting_fact: 'Speak four languages fluently'
  },
  {
    education_level: 'master',
    school: 'Chicago Booth',
    industry: 'Finance',
    job_title: 'Private Equity Associate',
    company: 'KKR',
    ethnicity: 'Indian',
    nationality: 'Indian',
    religion: 'Hindu',
    relationship_status: 'single',
    height_feet: 6,
    height_inches: 0,
    personality_traits: ['Strategic', 'Confident', 'Analytical'],
    mbti_type: 'ESTJ',
    lead_conversations: 4,
    willing_compromise: 3,
    seek_experiences: 4,
    roles: ['Host', 'Connector'],
    conversation_style: 'Professional',
    early_bird_night_owl: 2,
    active_person: 4,
    punctuality: 5,
    work_life_balance: 3,
    substances: ['Alcohol'],
    dietary_restrictions: 'Vegetarian',
    food_budget: 70,
    spicy_level: 5,
    drinking_level: 3,
    adventurous_level: 3,
    dining_atmospheres: ['fine_dining', 'business'],
    dinner_duration: '90+ min',
    zip_code: '94105',
    travel_distance: 8,
    food_craving: 'Indian cuisine',
    cuisines_to_try: ['Thai', 'Mexican', 'Mediterranean'],
    cuisines_to_avoid: ['Meat-heavy cuisines'],
    interests: ['Private equity', 'Startups', 'Cricket', 'Travel'],
    hobbies: ['Cricket', 'Reading business books', 'Yoga'],
    hoping_to_meet: 'Entrepreneurs and investors',
    interesting_fact: 'Evaluated over 50 startup investments'
  },
  {
    education_level: 'bachelor',
    school: 'UC Berkeley',
    industry: 'Finance',
    job_title: 'Venture Capitalist',
    company: 'Sequoia Capital',
    ethnicity: 'White',
    nationality: 'American',
    religion: 'Atheist',
    relationship_status: 'married',
    height_feet: 5,
    height_inches: 8,
    personality_traits: ['Visionary', 'Risk-taker', 'Networker'],
    mbti_type: 'ENTP',
    lead_conversations: 5,
    willing_compromise: 3,
    seek_experiences: 5,
    roles: ['Connector', 'Question-asker'],
    conversation_style: 'Engaging',
    early_bird_night_owl: 3,
    active_person: 3,
    punctuality: 3,
    work_life_balance: 3,
    substances: ['Alcohol', 'Weed'],
    dietary_restrictions: 'Keto',
    food_budget: 75,
    spicy_level: 3,
    drinking_level: 4,
    adventurous_level: 5,
    dining_atmospheres: ['lively', 'innovative'],
    dinner_duration: '90+ min',
    zip_code: '94301',
    travel_distance: 10,
    food_craving: 'Innovative fusion cuisine',
    cuisines_to_try: ['Molecular gastronomy', 'Nordic', 'Fusion'],
    cuisines_to_avoid: ['Heavy carbs'],
    interests: ['Startups', 'Innovation', 'Future tech', 'Angel investing'],
    hobbies: ['Angel investing', 'Kitesurfing', 'Podcast hosting'],
    hoping_to_meet: 'Founders and innovators',
    interesting_fact: 'Invested in 3 unicorn companies'
  },

  // Group 3: Healthcare Professionals (3 users) - Similar values, different specialties
  {
    education_level: 'doctorate',
    school: 'UCSF',
    industry: 'Healthcare',
    job_title: 'Emergency Medicine Doctor',
    company: 'Stanford Hospital',
    ethnicity: 'Hispanic',
    nationality: 'Mexican',
    religion: 'Catholic',
    relationship_status: 'married',
    height_feet: 5,
    height_inches: 10,
    personality_traits: ['Compassionate', 'Decisive', 'Resilient'],
    mbti_type: 'ESFJ',
    lead_conversations: 3,
    willing_compromise: 4,
    seek_experiences: 3,
    roles: ['Storyteller', 'Comic relief'],
    conversation_style: 'Direct',
    early_bird_night_owl: 3,
    active_person: 4,
    punctuality: 5,
    work_life_balance: 3,
    substances: ['Alcohol'],
    dietary_restrictions: '',
    food_budget: 55,
    spicy_level: 5,
    drinking_level: 3,
    adventurous_level: 3,
    dining_atmospheres: ['casual', 'lively'],
    dinner_duration: '45-90 min',
    zip_code: '94305',
    travel_distance: 6,
    food_craving: 'Authentic tacos',
    cuisines_to_try: ['Peruvian', 'Colombian', 'Cuban'],
    cuisines_to_avoid: ['Raw fish'],
    interests: ['Medicine', 'Public health', 'Soccer', 'Family'],
    hobbies: ['Soccer', 'Cooking', 'Volunteering'],
    hoping_to_meet: 'Healthcare professionals and community advocates',
    interesting_fact: 'Saved over 1000 lives in the ER'
  },
  {
    education_level: 'master',
    school: 'Johns Hopkins',
    industry: 'Healthcare',
    job_title: 'Clinical Research Coordinator',
    company: 'Genentech',
    ethnicity: 'Black',
    nationality: 'American',
    religion: 'Baptist',
    relationship_status: 'single',
    height_feet: 5,
    height_inches: 4,
    personality_traits: ['Methodical', 'Patient', 'Caring'],
    mbti_type: 'ISFP',
    lead_conversations: 2,
    willing_compromise: 5,
    seek_experiences: 3,
    roles: ['Quiet observer', 'Question-asker'],
    conversation_style: 'Gentle',
    early_bird_night_owl: 2,
    active_person: 3,
    punctuality: 5,
    work_life_balance: 4,
    substances: ['None'],
    dietary_restrictions: '',
    food_budget: 40,
    spicy_level: 3,
    drinking_level: 1,
    adventurous_level: 3,
    dining_atmospheres: ['quiet', 'casual'],
    dinner_duration: '30-45 min',
    zip_code: '94080',
    travel_distance: 5,
    food_craving: 'Soul food',
    cuisines_to_try: ['Ethiopian', 'Caribbean', 'Creole'],
    cuisines_to_avoid: ['Very experimental'],
    interests: ['Medical research', 'Public health', 'Gospel music'],
    hobbies: ['Singing', 'Reading', 'Community service'],
    hoping_to_meet: 'People passionate about healthcare',
    interesting_fact: 'Coordinated trials for breakthrough cancer treatments'
  },
  {
    education_level: 'doctorate',
    school: 'Stanford Medical',
    industry: 'Healthcare',
    job_title: 'Psychiatrist',
    company: 'Private Practice',
    ethnicity: 'White',
    nationality: 'Canadian',
    religion: 'Spiritual',
    relationship_status: 'divorced',
    height_feet: 6,
    height_inches: 2,
    personality_traits: ['Empathetic', 'Insightful', 'Calm'],
    mbti_type: 'INFP',
    lead_conversations: 3,
    willing_compromise: 5,
    seek_experiences: 4,
    roles: ['Question-asker', 'Quiet observer'],
    conversation_style: 'Reflective',
    early_bird_night_owl: 2,
    active_person: 3,
    punctuality: 4,
    work_life_balance: 5,
    substances: ['Weed'],
    dietary_restrictions: 'Plant-based',
    food_budget: 60,
    spicy_level: 2,
    drinking_level: 2,
    adventurous_level: 4,
    dining_atmospheres: ['quiet', 'peaceful'],
    dinner_duration: '90+ min',
    zip_code: '94022',
    travel_distance: 7,
    food_craving: 'Fresh salads and smoothies',
    cuisines_to_try: ['Raw food', 'Ayurvedic', 'Macrobiotic'],
    cuisines_to_avoid: ['Heavy meat dishes'],
    interests: ['Mental health', 'Mindfulness', 'Philosophy', 'Nature'],
    hobbies: ['Meditation', 'Hiking', 'Writing'],
    hoping_to_meet: 'Deep thinkers and wellness enthusiasts',
    interesting_fact: 'Written a bestselling book on mindfulness'
  },

  // Group 4: Creative Professionals (4 users) - Artistic souls with varied expressions
  {
    education_level: 'bachelor',
    school: 'Rhode Island School of Design',
    industry: 'Creative',
    job_title: 'Graphic Designer',
    company: 'IDEO',
    ethnicity: 'Mixed',
    nationality: 'American',
    religion: 'None',
    relationship_status: 'dating',
    height_feet: 5,
    height_inches: 7,
    personality_traits: ['Creative', 'Expressive', 'Open-minded'],
    mbti_type: 'ENFP',
    lead_conversations: 4,
    willing_compromise: 4,
    seek_experiences: 5,
    roles: ['Storyteller', 'Comic relief'],
    conversation_style: 'Animated',
    early_bird_night_owl: 4,
    active_person: 3,
    punctuality: 2,
    work_life_balance: 4,
    substances: ['Alcohol', 'Weed'],
    dietary_restrictions: '',
    food_budget: 35,
    spicy_level: 4,
    drinking_level: 4,
    adventurous_level: 5,
    dining_atmospheres: ['artistic', 'lively'],
    dinner_duration: '90+ min',
    zip_code: '94110',
    travel_distance: 8,
    food_craving: 'Street food',
    cuisines_to_try: ['Vietnamese', 'Filipino', 'West African'],
    cuisines_to_avoid: ['Chain restaurants'],
    interests: ['Art', 'Design', 'Music', 'Street culture'],
    hobbies: ['Painting', 'DJ-ing', 'Thrift shopping'],
    hoping_to_meet: 'Artists and creative thinkers',
    interesting_fact: 'Had my art displayed in MoMA'
  },
  {
    education_level: 'master',
    school: 'USC Film School',
    industry: 'Entertainment',
    job_title: 'Film Director',
    company: 'Netflix',
    ethnicity: 'Asian',
    nationality: 'Korean',
    religion: 'None',
    relationship_status: 'single',
    height_feet: 5,
    height_inches: 9,
    personality_traits: ['Visionary', 'Intense', 'Perfectionist'],
    mbti_type: 'INTJ',
    lead_conversations: 4,
    willing_compromise: 2,
    seek_experiences: 5,
    roles: ['Storyteller', 'Host'],
    conversation_style: 'Passionate',
    early_bird_night_owl: 5,
    active_person: 2,
    punctuality: 3,
    work_life_balance: 2,
    substances: ['Alcohol', 'Tobacco'],
    dietary_restrictions: '',
    food_budget: 50,
    spicy_level: 5,
    drinking_level: 4,
    adventurous_level: 4,
    dining_atmospheres: ['atmospheric', 'unique'],
    dinner_duration: '90+ min',
    zip_code: '94041',
    travel_distance: 10,
    food_craving: 'Korean BBQ',
    cuisines_to_try: ['Omakase', 'Michelin starred', 'Underground supper clubs'],
    cuisines_to_avoid: ['Bland food'],
    interests: ['Cinema', 'Storytelling', 'Photography', 'Culture'],
    hobbies: ['Film analysis', 'Script writing', 'Photography'],
    hoping_to_meet: 'Storytellers and film enthusiasts',
    interesting_fact: 'Won Sundance Film Festival award'
  },
  {
    education_level: 'bachelor',
    school: 'Berklee College of Music',
    industry: 'Music',
    job_title: 'Music Producer',
    company: 'Freelance',
    ethnicity: 'Black',
    nationality: 'British',
    religion: 'None',
    relationship_status: 'single',
    height_feet: 6,
    height_inches: 0,
    personality_traits: ['Collaborative', 'Innovative', 'Laid-back'],
    mbti_type: 'ISFP',
    lead_conversations: 3,
    willing_compromise: 5,
    seek_experiences: 5,
    roles: ['Comic relief', 'Connector'],
    conversation_style: 'Chill',
    early_bird_night_owl: 5,
    active_person: 3,
    punctuality: 2,
    work_life_balance: 4,
    substances: ['Alcohol', 'Weed'],
    dietary_restrictions: '',
    food_budget: 40,
    spicy_level: 3,
    drinking_level: 4,
    adventurous_level: 5,
    dining_atmospheres: ['lively', 'music venues'],
    dinner_duration: '90+ min',
    zip_code: '94109',
    travel_distance: 8,
    food_craving: 'Caribbean food',
    cuisines_to_try: ['Jamaican', 'Brazilian', 'African'],
    cuisines_to_avoid: ['Pretentious fine dining'],
    interests: ['Music production', 'Live shows', 'Sound design', 'Vinyl'],
    hobbies: ['DJ-ing', 'Record collecting', 'Live music'],
    hoping_to_meet: 'Musicians and music lovers',
    interesting_fact: 'Produced tracks for Grammy-nominated artists'
  },
  {
    education_level: 'bachelor',
    school: 'Parsons',
    industry: 'Fashion',
    job_title: 'Fashion Designer',
    company: 'Levi Strauss & Co',
    ethnicity: 'White',
    nationality: 'French',
    religion: 'None',
    relationship_status: 'dating',
    height_feet: 5,
    height_inches: 11,
    personality_traits: ['Aesthetic', 'Trendy', 'Detail-oriented'],
    mbti_type: 'ESFP',
    lead_conversations: 4,
    willing_compromise: 3,
    seek_experiences: 5,
    roles: ['Host', 'Storyteller'],
    conversation_style: 'Sophisticated',
    early_bird_night_owl: 3,
    active_person: 4,
    punctuality: 4,
    work_life_balance: 3,
    substances: ['Alcohol'],
    dietary_restrictions: '',
    food_budget: 65,
    spicy_level: 2,
    drinking_level: 4,
    adventurous_level: 4,
    dining_atmospheres: ['fine_dining', 'trendy'],
    dinner_duration: '90+ min',
    zip_code: '94108',
    travel_distance: 7,
    food_craving: 'French cuisine',
    cuisines_to_try: ['Modern French', 'Italian', 'Spanish'],
    cuisines_to_avoid: ['Fast food'],
    interests: ['Fashion', 'Art', 'Photography', 'Travel'],
    hobbies: ['Fashion shows', 'Vintage shopping', 'Pilates'],
    hoping_to_meet: 'Creative professionals and fashion enthusiasts',
    interesting_fact: 'Designed a collection shown at Paris Fashion Week'
  },

  // Group 5: Academics & Educators (4 users) - Knowledge seekers and sharers
  {
    education_level: 'doctorate',
    school: 'Harvard',
    industry: 'Education',
    job_title: 'Philosophy Professor',
    company: 'Stanford University',
    ethnicity: 'White',
    nationality: 'American',
    religion: 'Agnostic',
    relationship_status: 'married',
    height_feet: 5,
    height_inches: 10,
    personality_traits: ['Intellectual', 'Thoughtful', 'Curious'],
    mbti_type: 'INTP',
    lead_conversations: 4,
    willing_compromise: 4,
    seek_experiences: 4,
    roles: ['Question-asker', 'Quiet observer'],
    conversation_style: 'Socratic',
    early_bird_night_owl: 2,
    active_person: 2,
    punctuality: 4,
    work_life_balance: 4,
    substances: ['Alcohol'],
    dietary_restrictions: '',
    food_budget: 45,
    spicy_level: 2,
    drinking_level: 3,
    adventurous_level: 3,
    dining_atmospheres: ['quiet', 'intellectual'],
    dinner_duration: '90+ min',
    zip_code: '94305',
    travel_distance: 5,
    food_craving: 'Italian',
    cuisines_to_try: ['Greek', 'Turkish', 'Persian'],
    cuisines_to_avoid: ['Loud restaurants'],
    interests: ['Philosophy', 'Literature', 'History', 'Ethics'],
    hobbies: ['Reading', 'Writing', 'Chess'],
    hoping_to_meet: 'Intellectuals and deep thinkers',
    interesting_fact: 'Published 3 philosophy books'
  },
  {
    education_level: 'master',
    school: 'Columbia Teachers College',
    industry: 'Education',
    job_title: 'High School Science Teacher',
    company: 'Palo Alto High',
    ethnicity: 'Asian',
    nationality: 'Japanese',
    religion: 'Shinto',
    relationship_status: 'married',
    height_feet: 5,
    height_inches: 3,
    personality_traits: ['Patient', 'Enthusiastic', 'Nurturing'],
    mbti_type: 'ESFJ',
    lead_conversations: 3,
    willing_compromise: 5,
    seek_experiences: 3,
    roles: ['Connector', 'Host'],
    conversation_style: 'Encouraging',
    early_bird_night_owl: 1,
    active_person: 4,
    punctuality: 5,
    work_life_balance: 4,
    substances: ['None'],
    dietary_restrictions: '',
    food_budget: 35,
    spicy_level: 2,
    drinking_level: 2,
    adventurous_level: 3,
    dining_atmospheres: ['casual', 'family-friendly'],
    dinner_duration: '45-90 min',
    zip_code: '94306',
    travel_distance: 4,
    food_craving: 'Japanese comfort food',
    cuisines_to_try: ['Korean', 'Hawaiian', 'Taiwanese'],
    cuisines_to_avoid: ['Very heavy foods'],
    interests: ['Education', 'Science', 'Youth development', 'Nature'],
    hobbies: ['Gardening', 'Origami', 'Hiking'],
    hoping_to_meet: 'Educators and parents',
    interesting_fact: 'My students have won 5 state science fairs'
  },
  {
    education_level: 'doctorate',
    school: 'Oxford',
    industry: 'Research',
    job_title: 'Climate Scientist',
    company: 'Stanford Woods Institute',
    ethnicity: 'White',
    nationality: 'British',
    religion: 'None',
    relationship_status: 'single',
    height_feet: 6,
    height_inches: 1,
    personality_traits: ['Passionate', 'Analytical', 'Activist'],
    mbti_type: 'ENTJ',
    lead_conversations: 5,
    willing_compromise: 2,
    seek_experiences: 4,
    roles: ['Storyteller', 'Question-asker'],
    conversation_style: 'Urgent',
    early_bird_night_owl: 2,
    active_person: 5,
    punctuality: 5,
    work_life_balance: 3,
    substances: ['Alcohol'],
    dietary_restrictions: 'Vegan',
    food_budget: 40,
    spicy_level: 3,
    drinking_level: 3,
    adventurous_level: 4,
    dining_atmospheres: ['sustainable', 'casual'],
    dinner_duration: '45-90 min',
    zip_code: '94305',
    travel_distance: 6,
    food_craving: 'Plant-based cuisine',
    cuisines_to_try: ['Vegan sushi', 'Plant-based Mexican', 'Raw food'],
    cuisines_to_avoid: ['All animal products'],
    interests: ['Climate change', 'Sustainability', 'Policy', 'Outdoor sports'],
    hobbies: ['Rock climbing', 'Documentary making', 'Activism'],
    hoping_to_meet: 'Environmentalists and change-makers',
    interesting_fact: 'Testified before Congress on climate policy'
  },
  {
    education_level: 'doctorate',
    school: 'Yale',
    industry: 'Library Science',
    job_title: 'Head Librarian',
    company: 'San Francisco Public Library',
    ethnicity: 'Hispanic',
    nationality: 'Argentinian',
    religion: 'Catholic',
    relationship_status: 'divorced',
    height_feet: 5,
    height_inches: 8,
    personality_traits: ['Organized', 'Helpful', 'Knowledgeable'],
    mbti_type: 'ISTJ',
    lead_conversations: 2,
    willing_compromise: 4,
    seek_experiences: 3,
    roles: ['Quiet observer', 'Question-asker'],
    conversation_style: 'Informative',
    early_bird_night_owl: 2,
    active_person: 3,
    punctuality: 5,
    work_life_balance: 5,
    substances: ['Alcohol'],
    dietary_restrictions: '',
    food_budget: 40,
    spicy_level: 3,
    drinking_level: 3,
    adventurous_level: 3,
    dining_atmospheres: ['quiet', 'cozy'],
    dinner_duration: '45-90 min',
    zip_code: '94117',
    travel_distance: 5,
    food_craving: 'Argentinian steak',
    cuisines_to_try: ['Brazilian', 'Chilean', 'Uruguayan'],
    cuisines_to_avoid: ['Very loud places'],
    interests: ['Literature', 'History', 'Archives', 'Community service'],
    hobbies: ['Book clubs', 'Tango dancing', 'Wine tasting'],
    hoping_to_meet: 'Book lovers and history enthusiasts',
    interesting_fact: 'Curated a rare books collection worth $10M'
  }
];

async function createTestUserProfiles() {
  console.log('🚀 Starting to create test user profiles...\n');

  try {
    // First, get all test users
    const { data: users, error: usersError } = await supabase
      .from('users')
      .select('id, email, first_name, last_name')
      .like('email', '%@test.stanford.edu')
      .order('email');

    if (usersError) {
      console.error('❌ Error fetching users:', usersError);
      return;
    }

    console.log(`✅ Found ${users.length} test users\n`);

    // Create profiles for each user
    for (let i = 0; i < users.length && i < profileTemplates.length; i++) {
      const user = users[i];
      const template = profileTemplates[i];
      
      console.log(`📝 Creating profile for ${user.email}...`);

      // Check if profile already exists
      const { data: existingProfile } = await supabase
        .from('onboarding_profiles')
        .select('user_id')
        .eq('user_id', user.id)
        .single();

      if (existingProfile) {
        console.log(`   ⚠️  Profile already exists, updating...`);
        
        // Update existing profile
        const { error: updateError } = await supabase
          .from('onboarding_profiles')
          .update({
            ...template,
            updated_at: new Date().toISOString()
          })
          .eq('user_id', user.id);

        if (updateError) {
          console.error(`   ❌ Error updating profile:`, updateError);
        } else {
          console.log(`   ✅ Profile updated successfully`);
        }
      } else {
        // Insert new profile
        const { error: insertError } = await supabase
          .from('onboarding_profiles')
          .insert({
            user_id: user.id,
            ...template,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          });

        if (insertError) {
          console.error(`   ❌ Error creating profile:`, insertError);
        } else {
          console.log(`   ✅ Profile created successfully`);
        }
      }

      // Also update user's onboarding status to fully_complete
      const { error: statusError } = await supabase
        .from('users')
        .update({
          onboarding_status: 'fully_complete',
          onboarding_completed_at: new Date().toISOString()
        })
        .eq('id', user.id);

      if (statusError) {
        console.error(`   ⚠️  Failed to update onboarding status:`, statusError);
      }
    }

    console.log('\n✅ All test user profiles created successfully!');
    
    // Summary of groupings
    console.log('\n📊 Profile Summary:');
    console.log('Group 1: Tech Professionals (5 users) - Similar tech interests, varied food preferences');
    console.log('Group 2: Finance Professionals (4 users) - Business-minded, fine dining preferences');
    console.log('Group 3: Healthcare Workers (3 users) - Service-oriented, health-conscious');
    console.log('Group 4: Creative Professionals (4 users) - Artistic, adventurous eaters');
    console.log('Group 5: Academics & Educators (4 users) - Intellectual, cultural food interests');
    
    console.log('\nGroupable aspects:');
    console.log('- By Industry: Tech (5), Finance (4), Healthcare (3), Creative (4), Education (4)');
    console.log('- By Personality: Introverts vs Extroverts');
    console.log('- By Food Budget: Budget ($35-45), Mid-range ($45-60), High-end ($60-80)');
    console.log('- By Dining Style: Quick (30-45 min), Regular (45-90 min), Leisurely (90+ min)');
    console.log('- By Food Adventure: Conservative (1-3), Moderate (3-4), Adventurous (4-5)');
    console.log('- By Location: Grouped by zip codes in Peninsula, SF, South Bay');

  } catch (error) {
    console.error('❌ Unexpected error:', error);
  }
}

// Run the script
createTestUserProfiles();